GAME_CONFIG = {
    "title": "Tavern Rats: The Reliquary Heist (LLM Edition)",
    "starting_state": {
        "player": {
            "name": "You",
            "location": "tavern_common_room",
            "inventory": [],
            "health": 100,
            "strength": 5,
            "gold": 3,
        },
        "flags": {
            "intro_seen": False,
            "case_open": False,
            "reliquary_location_known": False,
            "sigil_decoded": False,
            "vault_opened": False,
            "reliquary_recovered": False,
            "escaped_with_reliquary": False,
            "guard_alert": 0,
            "rat_reputation": 0,
            "clue_tavern_rumor": False,
            "clue_smashed_crate": False,
            "clue_sigil_rubbing": False,
            "clue_forest_waystone": False,
            "clue_ledger_entry": False,
            "ending": "",
        },
        "memory": [],
        "long_term_memory": "",
        "quests": {
            "main_reliquary": {
                "stage": "start",
                "objective": "Find who stole the Reliquary of Saint Kestrel.",
                "completed": False,
                "failed": False,
            }
        },
        "npc_states": {
            "bartender_mara": {
                "met": False,
                "mood": "neutral",
                "location": "tavern_common_room",
                "notes": "Knows rumors; hates trouble; will clam up if guard_alert is high.",
            },
            "grimbold_bouncer": {
                "met": False,
                "mood": "neutral",
                "location": "tavern_common_room",
                "notes": "Not bright but loyal to Mara; reacts to violence.",
            },
            "traveler_sable": {
                "met": False,
                "mood": "neutral",
                "location": "tavern_common_room",
                "notes": "A courier who saw something near the docks; sells info for coin.",
            },
            "hooded_figure_voss": {
                "met": False,
                "mood": "neutral",
                "location": "tavern_common_room",
                "notes": "A fixer; offers risky shortcuts; may betray if reputation is low.",
            },
            "captain_reyne": {
                "met": False,
                "mood": "neutral",
                "location": "guardhouse",
                "notes": "Town guard captain; can deputize you if convinced; escalates guard_alert if lied to.",
            },
            "scribe_elin": {
                "met": False,
                "mood": "neutral",
                "location": "chapel_archive",
                "notes": "Archivist; can decode sigils if treated respectfully.",
            },
            "apothecary_nim": {
                "met": False,
                "mood": "neutral",
                "location": "apothecary",
                "notes": "Sells salves; knows poisons; hints about smugglers.",
            },
            "smuggler_boss_krail": {
                "met": False,
                "mood": "neutral",
                "location": "docks_warehouse",
                "notes": "Controls dockside; linked to the reliquary movement.",
            },
        },
        "world_map": {
            "tavern_common_room": ["tavern_backroom", "town_square"],
            "tavern_backroom": ["tavern_common_room", "alleyway"],
            "town_square": [
                "tavern_common_room",
                "market",
                "chapel_steps",
                "guardhouse",
                "docks_road",
            ],
            "market": ["town_square", "apothecary"],
            "apothecary": ["market"],
            "guardhouse": ["town_square"],
            "chapel_steps": ["town_square", "chapel_sanctuary", "chapel_archive"],
            "chapel_sanctuary": ["chapel_steps"],
            "chapel_archive": ["chapel_steps"],
            "alleyway": ["tavern_backroom", "docks_road", "sewer_entrance"],
            "sewer_entrance": ["alleyway", "sewer_tunnels"],
            "sewer_tunnels": ["sewer_entrance", "docks_warehouse_basement"],
            "docks_road": ["town_square", "alleyway", "docks"],
            "docks": ["docks_road", "docks_warehouse"],
            "docks_warehouse": ["docks", "docks_warehouse_basement"],
            "docks_warehouse_basement": [
                "docks_warehouse",
                "sewer_tunnels",
                "forest_edge",
            ],
            "forest_edge": ["docks_warehouse_basement", "forest_path"],
            "forest_path": ["forest_edge", "waystone_clearing"],
            "waystone_clearing": ["forest_path", "old_reliquary_ruins"],
            "old_reliquary_ruins": ["waystone_clearing"],
        },
        "events": [],
        "plot": "Premise: In the river-town of Brinehook, the chapel's sacred artifact—the Reliquary of Saint Kestrel—vanished during last night's storm. The town guard suspects smugglers, but the chapel suspects heresy. You are a broke regular at the tavern who overhears the wrong conversation at the right time.\n\nTone: grounded medieval-noir with dark humor. Low magic rumors, but the reliquary might be more than a bauble.\n\nThree-act structure:\nAct I (Hook): In the tavern, gather rumors and decide who to trust. Open the case by finding a concrete lead.\nAct II (Investigation): Track the reliquary through town power centers (chapel archives, docks, sewers, forest waystone). Build a clue chain; rising guard attention punishes reckless actions.\nAct III (Heist/Recovery): Break into the holding site (warehouse basement or old ruins) using either diplomacy, stealth, or force. Escape with the reliquary—or face capture.\n\nKey truths (do not contradict once established):\n- The reliquary was moved twice: from chapel -> docks network -> final cache (either warehouse basement or old ruins).\n- At least one NPC will lie to protect their interests; catching contradictions is part of play.\n- 'Guard alert' increases with violence, threats, obvious theft, or repeated lies to Captain Reyne.\n\nWin condition: reassemble enough evidence to locate the reliquary, recover it, and reach a safe public place (Town Square or Chapel Steps) with it.\nLose condition: health drops to 0 OR guard_alert reaches 5 and you are arrested with no leverage.\n",
    },
    "system_prompt": '\nYou are an interactive text-adventure engine that must output ONLY a single valid JSON object (no markdown, no code fences, no headings).\nThe JSON must have exactly two top-level keys:\n- "CHANGES": object\n- "TEXT": string\n\n"CHANGES" may include ONLY these optional keys (snake_case exactly):\n- inventory_add: list of strings\n- inventory_remove: list of strings\n- flags_set: object\n- location_set: string\n- quest_update: object\n- npc_mood_set: object\n- world_events: list (items can be objects)\n\nNever include extra debug sections like "JSON Output", "Player State", "Memory", "Your Turn", or additional top-level keys.\n\nHard rules:\n1) Location movement must respect the world map adjacency in state["world_map"].\n   - Only set location_set to an adjacent location.\n   - If the player asks to go somewhere non-adjacent, narrate that they must travel step-by-step and suggest nearby options.\n\n2) Maintain continuity.\n   - Inventory items must be coherent (no adding items from nowhere unless the TEXT clearly describes obtaining them).\n   - Remove inventory items only if the TEXT clearly describes losing/spending them.\n\n3) Use flags to track clue discovery and outcomes.\n   - Increment tension by setting flags_set: {"guard_alert": N} where N is an integer 0..5.\n   - Track reputation similarly: flags_set: {"rat_reputation": N} where N is an integer -3..3.\n\n4) Quest progression:\n   - Update quests via quest_update, e.g. {"main_reliquary": {"stage":"investigation","objective":"..."}}\n   - Mark completed or failed only when clearly earned.\n\n5) Endings:\n   - If the win condition is achieved, set flags_set: {"ending":"WIN","reliquary_recovered":true,"escaped_with_reliquary":true}\n     and write a satisfying closing in TEXT.\n   - If the lose condition is triggered, set flags_set: {"ending":"LOSE"} and close the story in TEXT.\n\nOutput style:\n- TEXT should be 120–220 words, second-person, with 2–4 actionable next steps phrased naturally (not as a numbered UI menu).\n- Keep NPC dialogue short and distinctive.\n- Avoid railroading: allow multiple solutions (talk/steal/sneak/fight), but enforce consequences.\n'.strip(),
}
